### PR TITLE
ChessBotPy.user.js: add elements used by chess.com beta

### PR DESCRIPTION
**Pull request by maxice8**
chess.com has a new beta mode and they use .move-list-component and
.move-component.

This is not complete, sideFinder () will need a rewrite as .board-player-default-bottom.board-player-default-black doesn't exist anymore.

I use:

```javascript
// Return the first coordinate-grey member, which should be the topmost 0
// if it is 1 then white is at the top and we are playing as black
// if it is 8 then white is at the bottom, we can't tell (atm) if the user has white always on bottom
// so assume that we are playing as white if white is on the bottom
(doc.querySelector('.coordinate-grey').textContent == 1 ? BLACK : WHITE)
```

### CODE REVIEW

**Comment by epoyx44** [comment]
did you run by the source code or the compiled one? because there is some glitch with the source code theres no way to run it..

**Comment by maxice8** [comment]
Source code

**Comment by epoyx44** [comment]
HI MaxicE ..did you actually run successfully the source code? But how? In
my case it didn't work I can't even see the board in the css tab.. it says
something went wrong keep trying.. while on the exe one.. I can run
successfully.. any idea what happened? Or maybe because of my python
version?

**Comment by maxice8** [comment]
> HI MaxicE ..did you actually run successfully the source code? 

Yes

> But how? 

```sh
$ python3 python/main.py
```

> In my case it didn't work I can't even see the board in the css tab.. 

Your chess engine needs to be loaded and have analysed the position for it to load the chess board, also make sure you configured it to not have "Pieces only" ticked.

> it says something went wrong keep trying.. while on the exe one.. I can run successfully.. any idea what happened?

No, I don't use Windows and I'm not support for ChessBotPy

**Comment by epoyx44** [comment]
Can you pleases take a look at this?
[image: 5.png]
[image: 10.png]
[image: Untitled.png]

**Comment by epoyx44** [comment]
Can you please take a look at this:  https://imgur.com/a/7F0uSRe

**Pull request merged**
